project:
  type: website

# Website Configuration and Layout
website:
  title: "STATS 13"
  description: "Introduction to Statistical Methods for Life and Health Sciences at UC Los Angeles"
  search:
    location: navbar
    type: overlay
  site-url: "https://ucla-stats13.netlify.app"
  repo-url: "https://github.com/toledo60/ucla-stats13"
  #favicon: assets/favicon.ico
  #image: assets/stat20-hex.png
  open-graph:
     site-name: "STATS 13"
  #  image: assets/stat20-hex.png
  twitter-card: true
  page-navigation: true
  reader-mode: true
  navbar:
    title: false
    #logo: assets/stat20-hex-small.png
    #logo-alt: "Stat 20 logo"
    background: white
    foreground: "gray-800"
    collapse-below: sm
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: schedule.qmd
      - text: Notes
        href: notes.qmd
      - text: Assignments
        href: assignments.qmd
    tools:
      - icon: github
        href: https://github.com/toledo60/ucla-stats13
        aria-label: Github
      - icon: r-circle-fill
        href: https://rstudio.stat.ucla.edu
        aria-label: RStudio
        
  page-footer: 
    background: white
    foreground: "gray-800"
    border: false
    right:
      - text: License
        href: license.qmd


# Format-specific Metadata
format:
  html:
    theme:
      - sandstone
      - assets/styles.scss
    toc: true
    published-title: "class date"
    reference-location: document
    code-fold: false
    code-link: true
    code-summary: ""

# General Metadata
execute:
  freeze: auto
  message: false
  warning: false
  fig-align: center
  
profile:
  default: toc