{
  "hash": "c84f239f57e5e3b6b159ff640390a1b0",
  "result": {
    "markdown": "---\ntitle: \"Summarizing Categorical Data\"\nauthor: Jose Toledo Luna\ntoc: true\ndate: October 27, 2023\n---\n\n::: {.cell}\n\n:::\n\n\n\nWe will use the `births` data set to summarize and visualize categorical variables using the *base R* approach\n\n\nCategorical data is a type of data that is divided into categories or groups, such as hair color or education level. Categorical data can be further divided into *nominal data*, which is data that has no inherent order, such as hair color, and *ordinal data*, which is data that has a defined order, such as education level\n\n\n\n## Single categorical variable\n\nOne way to extract all the character columns is using both `Filter` and `is.character` functions. A similar argument can be said for any columns that are factors, but instead we'd use `is.factor`. \n\nBelow are the first five rows of all the character columns in `birth_dat`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFilter(is.character,birth_dat)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n  Gender Premie   Marital Racemom Racedad   Hispmom   Hispdad     Habit\n1   Male     No   Married   White   White   Mexican   Mexican NonSmoker\n2   Male     No Unmarried   White Unknown   NotHisp   Unknown    Smoker\n3   Male     No   Married   White   White OtherHisp OtherHisp NonSmoker\n4   Male     No   Married   White   White   Mexican   Mexican NonSmoker\n5 Female     No Unmarried   Black Unknown   NotHisp   Unknown NonSmoker\n  MomPriorCond BirthDef    DelivComp BirthComp\n1         None     None         None      None\n2 At Least One     None         None      None\n3         None     None At Least One      None\n4         None     None At Least One      None\n5         None     None         None      None\n```\n:::\n:::\n\n\nThe names of the character columns can be obtained using `colnames()` function in combination with the above statement\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(Filter(is.character,birth_dat) )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Gender\"       \"Premie\"       \"Marital\"      \"Racemom\"      \"Racedad\"     \n [6] \"Hispmom\"      \"Hispdad\"      \"Habit\"        \"MomPriorCond\" \"BirthDef\"    \n[11] \"DelivComp\"    \"BirthComp\"   \n```\n:::\n:::\n\n\n\nWe will only consider the `Hispmom` variable from our dataset to demonstrate methods to summarize and visualize a character variable.\n\nFirst, we'll save the values from `Hispmom` column into a separate variable and compute several categorical summaries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhispanic_mom <- birth_dat$Hispmom\n```\n:::\n\n\nThe `table()` function in R can be used to quickly create frequency tables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hispanic_mom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhispanic_mom\n  Mexican   NotHisp OtherHisp \n      216      1697        85 \n```\n:::\n:::\n\n\nFrom the above frequency table we observe there were 25 mom who were Mexican, 1693 non Hispanic, and 84 were other types of Hispanic. We can easily convert the frequency table into a frequency table of proportions using `prop.table()`. The input for `prop.table()` is a table created using `table()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(hispanic_mom))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhispanic_mom\n   Mexican    NotHisp  OtherHisp \n0.10810811 0.84934935 0.04254254 \n```\n:::\n:::\n\n\nNow, we observe roughly 10.79% of moms were Mexican, 84.99% were non Hispanic and 4.22% were other types of Hispanic. Note that all of the proportions should add up to 1. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(prop.table(table(hispanic_mom)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n\nWhile the above method works, it is not the only way to obtain frequency tables. We can obtain the same results using `tally()` from the `mosaic` library.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::tally(hispanic_mom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nX\n  Mexican   NotHisp OtherHisp \n      216      1697        85 \n```\n:::\n:::\n\n\nIf we want frequency tables of proportions, we need to use the argument `format` and specify `format = 'proportion'`. There are other formats such as `'count'`, `'percent'` etc.. for more details run `?mosaicCore::tally()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::tally(hispanic_mom,format='proportion')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nX\n   Mexican    NotHisp  OtherHisp \n0.10810811 0.84934935 0.04254254 \n```\n:::\n:::\n\n\nTo plot a single categorical variable we can use `barplot()`. The input for `barplot()` when dealing with categorical data is a `table`, like the ones we created above\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(table(hispanic_mom))\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nInstead of the frequency counts, we can plot frequency of proportions by inputting a frequency tables of proportions. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(prop.table(table(hispanic_mom)),\n        main = 'Ethnicity Proportions of Moms',\n        col = '#d59cdb')\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n## Two categorical variables\n\nFor this example, we consider the following two character variables `Hispdad` and `Habit`. `Hispdad` determines whether the father of the baby was Hispanic or not. In particular, are they Mexican, non-Hispanic, or other type of Hispanic ethnicity. `Habit` determines whether or not the subject had a smoking habit or not.\n\nWhen dealing with two categorical variables we can create a two-way table using `table(v1,v2)`. Below is the table of frequency for both `Habit` and `Hispdad`.\n\n*Note: We save the table as a variable so we can use it later*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmoker_hispanic_dad <- table(birth_dat$Habit,birth_dat$Hispdad)\nsmoker_hispanic_dad\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n            Mexican NotHisp OtherHisp Unknown\n                  0       4         0       2\n  NonSmoker     184    1236        78     307\n  Smoker          5     117         2      63\n```\n:::\n:::\n\n\nFrom the above frequency table of counts you will notice that there were 184 Mexican dads who were non-smokers, 5 Mexican dads who were smokers, 1236 non-Hispanics who were non-smokers, 117 non-Hispanics who were smokers and similar interpretations can be made for the remaining cells.\n\nWe can obtain a table of proportions using `prop.table()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(smoker_hispanic_dad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n                Mexican     NotHisp   OtherHisp     Unknown\n            0.000000000 0.002002002 0.000000000 0.001001001\n  NonSmoker 0.092092092 0.618618619 0.039039039 0.153653654\n  Smoker    0.002502503 0.058558559 0.001001001 0.031531532\n```\n:::\n:::\n\n\n\nNow, lets plot the results of our table using the default `barplot` settings\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(smoker_hispanic_dad)\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nIt is difficult to understand the meaning of the black and gray filled sections of the barplot. Although we may have a general understanding that the gray portion represents smokers and the black portion represents non-smokers based on the accompanying table, we should not assume that the reader will automatically make this connection.\n\nWe can add a legend by using the argument `legend.text=TRUE`, and `barplot` will use the row names of our table to make the legend. Moreover, we add appropriate labels to our plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(smoker_hispanic_dad,\n        legend.text = TRUE,\n        xlab = 'Ethnicity',\n        ylab = 'Counts')\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nThe above figure shows a stacked bar plot. If we wanted the bars next to each other, rather than on top of each other, we can use the argument `beside=TRUE`. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(smoker_hispanic_dad,\n        legend.text = TRUE,\n        beside = TRUE,\n        xlab = 'Ethnicity',\n        ylab = 'Counts')\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nIt is evident that the number of non-smokers exceeds that of smokers across all ethnicities. However, we may be able to obtain a more comprehensive understanding of the data by altering the grouping order of the bars. Specifically, we should examine which ethnic group has a higher count for each smoking category.\n\n\nWe can change the order of our table by taking the *transpose*, that is we swap the columns and rows. In R, we can transpose any table-like object using the function `t()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt(smoker_hispanic_dad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           \n                 NonSmoker Smoker\n  Mexican      0       184      5\n  NotHisp      4      1236    117\n  OtherHisp    0        78      2\n  Unknown      2       307     63\n```\n:::\n:::\n\n\nFrom this point of view, we can observe the number of counts in each smoking habit category for each ethnicity. For example, there were 184 Mexican fathers who are non-smokers and 5 Mexican fathers that did smoke. Similar, interpretations can be made for other ethnic groups.\n\nWe can now use `barplot` on this new transposed table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(t(smoker_hispanic_dad),\n        legend.text = TRUE,\n        beside = TRUE,\n        xlab = 'Smoking Habit',\n        ylab = 'Counts')\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWe can clearly see the non-Hispanic fathers make up the highest counts for non-smokers and smokers. While the default color palette is color-blind friendly it can be hard to distinguish the categories based on these colors. \n\n\nWith a quick google search of  \"four color palettes\" you can find great palettes for 4 categories. For example, the following color palette was obtain from [colorhunt.co](https://colorhunt.co)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(t(smoker_hispanic_dad),\n        legend.text = TRUE,\n        col =c('#4E6E81','#F9DBBB','#FF0303','#2E3840'),\n        beside = TRUE,\n        xlab = 'Smoking Habit',\n        ylab = 'Counts')\n```\n\n::: {.cell-output-display}\n![](04-intro_categorical_variables_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "04-intro_categorical_variables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}